name: miketaylrdotcom
permalink: /:year/:month/:title.html
markdown: redcarpet
highlighter: rouge

# Used for my rss.xml template
name: Mike Taylr Dot Com Web Log
url: https://miketaylr.com/posts
description: Erotic web browser fan-fiction.
copyright: 3000
author: Mike Taylor
